app = "aai-medical-scribe-pipecat-client"
primary_region = "iad"

[build]
  [build.args]
    NEXT_PUBLIC_BACKEND_URL = "https://aai-medical-scribe-pipecat.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 2
